sudo: required
language: android
jdk:
- oraclejdk7
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
android:
  components:
  - tools
  - android-23
  - platform-tools
  - build-tools-23.0.3
  - extra-android-m2repository
  licenses:
  - android-sdk-license-[0-9a-f]{7}
  - android-sdk-preview-license-[0-9a-f]{7}
branches:
  only:
  - master
env:
  matrix:
  - COMPONENT=firecrasher
  - COMPONENT=app
script:
  - gradle clean check
  
